---
title: "Information Dynamic Measures"
author: Odalys Barrientos
output: html_notebook
---

```{r}
library(readr)
InfoM <- read_csv("transCSSR-master/InfoMeasuresData.csv")
#View(InfoM)

UserIDs <- read_csv("Username-IDs/UserIDs.csv")

InfoM$category <- UserIDs$category
```
```{r}
# Entropy: How random? (1 = random)
hist(InfoM$Hmu, breaks= "FD")
rug(InfoM$Hmu)

# Memory: How much info is shared from the past"?
hist(InfoM$E, breaks= "FD")
rug(InfoM$E)

# Complicated: How many bits of the past do we have to remember to predict the future?
hist(InfoM$Cmu, breaks= "FD")
rug(InfoM$Cmu)
```

```{r}
library(mosaic)

favstats(InfoM$Hmu)
favstats(~Hmu|category, data = InfoM)

favstats(InfoM$E)
favstats(~E|category, data = InfoM)

favstats(InfoM$Cmu)
favstats(~Cmu|category, data = InfoM)
```


```{r}
library(ggplot2)
ggplot(InfoM, aes(x=category, y = Hmu, group = category, col = category)) + geom_boxplot()

ggplot(InfoM, aes(x=category, y = E, group = category, col = category)) + geom_boxplot()

ggplot(InfoM, aes(x=category, y = Cmu, group = category, col = category)) + geom_boxplot()
```

```{r}
ggplot(InfoM, aes(x=Hmu, y = ..density.. , group = category, col = category)) + geom_density()

ggplot(InfoM, aes(x=E, y = ..density.. , group = category, col = category)) + geom_density()

ggplot(InfoM, aes(x=Cmu, y = ..density.. , group = category, col = category)) + geom_density()

```
```{r}
which(max(InfoM$Hmu) == InfoM$Hmu) # max entropy rate in this sample = 0.327
InfoM$category[14] # Famous 
# by looking at favstats "famous" users had the highest average entropy rate meaning they should be the hardest to predict
# they are more random than the other category of users

which(max(InfoM$E) == InfoM$E) 
InfoM$category[9] # Famous
# by looking at favstats "famous" users had the highest average "memory??" meaning they had the most info shared between the past and the future

which(max(InfoM$Cmu) == InfoM$Cmu) 
InfoM$category[4] # ForYou
# by looking at favstats "ForYou" users had the highest average "Cmu" meaning they had the most complicated/ sophisticated models (had to look further in the past to predict)
```

```{r}
plot(InfoM$Hmu, InfoM$Cmu)


library(e1071); library(ggplot2)

qplot(Hmu, Cmu, colour = category, data = InfoM)
qplot(Hmu, E, colour = category, data = InfoM)
qplot(Cmu, E, colour = category, data = InfoM)
```

